### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.table#3]
After this package was ported to Python 3 (see #2) it would be nice to have a new release on PyPI. I'd volunteer to create the release but I do not have the necessary permissions over there.

I am `icemac` on PyPI could someone of the package owners give me release rights, please?

@zvezdan @davisagli @freddrake @frisi @strichter @tlotze (Sorry for the long list, I am not sure who has currently time to do me this favor.)

**Comment by frisi** [comment]
done @icemac - thanks for your efforts!

**Comment by icemac** [comment]
@frisi Thank you. Just released https://pypi.org/project/zc.table/0.10.0/
